# Cloud Run Service Configuration for INTELLISEARCH
# Deploy: gcloud run services replace cloudrun-service.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: intellisearch
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/execution-environment: gen2
      annotations:
        # Scaling configuration
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        
        # Resource allocation
        run.googleapis.com/cpu: "2"
        run.googleapis.com/memory: "4Gi"
        run.googleapis.com/execution-environment: gen2
        
        # Timeout and startup
        run.googleapis.com/timeout: "3600"
        run.googleapis.com/startup-cpu-boost: "true"
        
        # Security and networking
        run.googleapis.com/vpc-access-connector: ""
        run.googleapis.com/vpc-access-egress: all
        
    spec:
      containerConcurrency: 100
      timeoutSeconds: 3600
      serviceAccountName: intellisearch-service-account
      
      containers:
      - name: intellisearch-container
        image: gcr.io/gen-lang-client-0665888431/intellisearch:latest
        
        ports:
        - name: http1
          containerPort: 8080
          protocol: TCP
          
        env:
        # Application configuration
        - name: PORT
          value: "8080"
        - name: ENVIRONMENT
          value: "production"
        - name: PRODUCTION_MODE
          value: "true"
          
        # Python configuration
        - name: PYTHONPATH
          value: "/app/src"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONDONTWRITEBYTECODE
          value: "1"
          
        # API Keys (set via Secret Manager)
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: google-api-key
              key: latest
        - name: SERPER_API_KEY
          valueFrom:
            secretKeyRef:
              name: serper-api-key
              key: latest
              
        # Performance optimizations for Cloud Run
        - name: LLM_TEMPERATURE
          value: "0.1"
        - name: MAX_TOKENS
          value: "30000"
        - name: MAX_SEARCH_QUERIES
          value: "8"
        - name: MAX_SEARCH_RESULTS
          value: "8"
        - name: MAX_CONCURRENT_SCRAPES
          value: "4"
        - name: CACHE_ENABLED
          value: "true"
        - name: CACHE_TTL
          value: "3600"
        - name: DEBUG_MODE
          value: "false"
          
        # Cloud Run specific settings
        - name: USE_ENHANCED_EMBEDDINGS
          value: "true"
        - name: USE_HYBRID_RETRIEVAL
          value: "true"
        - name: USE_CROSS_ENCODER_RERANKING
          value: "false"  # Disabled for better performance
        
        # Health check endpoint
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          
        # Resource requests and limits
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
            
        # Startup probe for long initialization
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30  # Allow up to 5 minutes for startup
          
  traffic:
  - percent: 100
    latestRevision: true